import { Geist, Roboto_Mono } from "next/font/google";
import "./globals.css";
import NextAuthProviders from "@/Providers/NextAuthProviders";
import Navbar from "@/components/shared/Navbar";
import ThemeProviders from "@/Providers/ThemeProvider";
import { Toaster } from "sonner";


export const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning data="">
     
      <body className={` ${roboto_mono.className}`}>
        <NextAuthProviders>
          <ThemeProviders
           
          >
            <Navbar />
            {children}
            <Toaster position="top-center" richColors  />
          </ThemeProviders>
        </NextAuthProviders>
      </body>
    </html>
  );
}
